/**
 * Created by brandon.flowers on 9/28/17.
 */

// CABINQUEST

export const CABINQUEST_SET_USER = 'CABINQUEST_SET_USER';

export const FEED_CABINQUEST_POST_TREE = 'FEED_CABINQUEST_POST_TREE';
export const FEED_CABINQUEST_POST_TREE_REQUEST =
    'FEED_CABINQUEST_POST_TREE_REQUEST';
export const FEED_CABINQUEST_POST_TREE_RECEIVED_SUCCESS =
    'FEED_CABINQUEST_POST_TREE_RECEIVED_SUCCESS';
export const FEED_CABINQUEST_POST_TREE_RECEIVED_FAIL =
    'FEED_CABINQUEST_POST_TREE_RECEIVED_FAIL';

export const FEED_CABINQUEST_GET_TREES = 'FEED_CABINQUEST_GET_TREES';
export const FEED_CABINQUEST_GET_TREES_REQUEST =
    'FEED_CABINQUEST_GET_TREES_REQUEST';
export const FEED_CABINQUEST_GET_TREES_RECEIVED_SUCCESS =
    'FEED_CABINQUEST_GET_TREES_RECEIVED_SUCCESS';
export const FEED_CABINQUEST_GET_TREES_RECEIVED_FAIL =
    'FEED_CABINQUEST_GET_TREES_RECEIVED_FAIL';

export const FEED_CABINQUEST_GET_PARK = 'FEED_CABINQUEST_GET_PARK';
export const FEED_CABINQUEST_GET_PARK_REQUEST =
    'FEED_CABINQUEST_GET_PARK_REQUEST';
export const FEED_CABINQUEST_GET_PARK_RECEIVED_SUCCESS =
    'FEED_CABINQUEST_GET_PARK_RECEIVED_SUCCESS';
export const FEED_CABINQUEST_GET_PARK_RECEIVED_FAIL =
    'FEED_CABINQUEST_GET_PARK_RECEIVED_FAIL';

export const FEED_CABINQUEST_POST_DEFAULT_PARK_REQUEST =
    'FEED_CABINQUEST_POST_DEFAULT_PARK_REQUEST';
export const FEED_CABINQUEST_POST_DEFAULT_PARK_SUCCESS =
    'FEED_CABINQUEST_POST_DEFAULT_PARK_SUCCESS';
export const FEED_CABINQUEST_POST_DEFAULT_PARK_FAIL =
    'FEED_CABINQUEST_POST_DEFAULT_PARK_FAIL';

// PORTHOLE

export const FEED_PORTHOLE_GET_FOREST = 'FEED_PORTHOLE_GET_FOREST';
export const FEED_PORTHOLE_GET_FOREST_REQUEST =
    'FEED_PORTHOLE_GET_FOREST_REQUEST';
export const FEED_PORTHOLE_GET_FOREST_RECEIVED_SUCCESS =
    'FEED_PORTHOLE_GET_FOREST_RECEIVED_SUCCESS';
export const FEED_PORTHOLE_GET_FOREST_RECEIVED_FAIL =
    'FEED_PORTHOLE_GET_FOREST_RECEIVED_FAIL';
